travis:
  secure:
    BINSTAR_TOKEN: Is+ShdGEUrk25WSXWVe+YM7lwFahfxTSA55hpjXPDrFweafV3NZJEHmr/GwXSYvcCDBw4aTvCyVcBHOy28fA+7csyO8DNpDhsc15VoUWIFt7XOHypslzNR2j1uMaxn3FBpFuXLt2wf4hYYq5y2EXX3Sewh+fGvuzdyzAa3t01oXtiZCTwjIoby+GOQxjwsqxI24SigFYcVG+LfM2Ph/hR127hFJlmcXJXXsRqEj2tFBf537KsgXagywxh4lKUP86xuwkWbIOM3mGpnJLL0WRyv8Sa8yqMRdQmuyd3YYQDXIm+haPnrudOGuayUfyQRe63BCbw8e8/3UouMkN5ZcXvyK3DoRpltxvK3xEJFYpgU5GdbE8apMzBxivu0lqIL+eqHat9MqEj1EqINo7S+MS2uSgvxKm4nqNe95TpftsgcD58SrFzJeOEa3vwzeOstP/ues0DV5IeLWvMFcACnM2TkNz/AFFoCPaTZ21LHrod5GuTexuWiwFGsAD3t356T6GtM4MjqdMFV3FArvK9k/GzCgKXT1RoFcIv8COne7ZnqShZTNZvOXyIDz8X/r5AgY/YNm7oQKIdy/XoO23TMIR1SbL98OW6EEXUvFK0BeePtgTEHNSALWuzD/ThDy6Fyveojeaz1i0Ks+d4Jl55q7Pg7VCEKdU9OXXNwjJl5cPCPM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
